### ISSUE TITLE
Tradução/MeiosDePagamentos/CPF

### ISSUE THREAD

**Issue by MarceloFullStack** [bagistobrasil/forum#1]
Como traduzir o bagisto e usar os meios de pagamentos brasileiros ? E sobre CPF ?

**Comment by cagartner** [comment]
Opa e ai @fotofacil .

O Bagisto já contém tradução para Português inclusa nele veja aqui como configurar ela na sua instalação: https://bagisto.com.br/post/configurando-bagisto-pt-br

Sobre o CPF, eu desenvolvi um módulo que adicionar essa informação no cadastro de cliente, porém irei mudar em breve, mas se quiser usar basta instalar essa extensão aqui: https://github.com/cagartner/bagisto-brazilcustomer

Espero ter ajudado.

Abraços!

**Comment by cagartner** [comment]
A esqueci de falar sobre os meios de pagamento, ao momento foram desenvolvidos os seguintes meios de pagamento:

Pagseguro: https://github.com/cagartner/bagisto-pagseguro
Picpay: https://github.com/cagartner/bagisto-picpay
Moip: https://github.com/roneclay/bagisto-moip-payment
Moip (Wirecard): https://github.com/arthurzanella/bagisto-wirecard
