### ISSUE TITLE
O Bagisto Brasil acabou?

### ISSUE THREAD

**Issue by highotz** [bagistobrasil/forum#5]
Precisava acessar a pagina sobre a traducao para pt-br e outras coisas

**Comment by cagartner** [comment]
Basicamente sim

**Comment by highotz** [comment]
tem alguma forma de acessar os conteudos que tinha la?

**Comment by highotz** [comment]
Tranquilo, vlw pela atencao!

Seus pocotes ja ajudaram pra krl
